### ISSUE TITLE
Examples for synchronous ChimpJS API

### ISSUE THREAD

**Issue by orlade** [cjsauer/accounts-phony#2]
[ChimpJS has a synchronous API](https://chimp.readme.io/docs/synchronous-tests), so the code samples in the README don't work. Here's what I'm doing in CoffeeScript:

``` coffee
module.exports = ->

  ROOT_URL = 'http://localhost:3000'
  login = (done) -> Meteor.loginWithPhony Package['csauer:accounts-phony'].Phony.user, done

  @Given 'I am logged in', ->
    @browser.url(ROOT_URL)
    @browser.timeoutsAsyncScript(5000)
    @browser.executeAsync(login)

  @Given 'I am on the Dashboard', -> @browser.url("#{ROOT_URL}/dashboard")

  @Then 'I can see my widgets', -> @browser.waitForExist("<my DOM selector>").should.equal(true)
```

Note: This is running with `--chai` so uses `should` instead of Jasmine's `expect()`.

Also I probably shouldn't be writing `localhost:3000`, but that's another story.

**Comment by cjsauer** [comment]
Updated readme in commit 072d0d6, thanks for the heads up!

Also you can retrieve the root URL using `process.env.ROOT_URL`. Should make your code a bit more generic.
