### ISSUE TITLE
Meteor.user() returns undefined

### ISSUE THREAD

**Issue by martpie** [cjsauer/accounts-phony#3]
Hello, 

I think I just need a clarification, because I'm not sure about what I can do with this package, and what I cannot do.

I need to "fake a login" in Meteor to unit-test roles and page access. So I'm logging with Phony, `Meteor.userId()` returns the correct _id of the fake user I logged in, but `Meteor.user()` returns `undefined`

Have I done something wrong or is this package not about the problem I try to solve?

**Comment by cjsauer** [comment]
Hello KeitIG,

Can you tell me what user object you're passing into the `Meteor.loginWithPhony()` method? It should be the first argument, as shown in the [readme](https://github.com/cjsauer/accounts-phony/blob/master/README.md#how-to-use). That object is what will be set as the `Meteor.user()` object. If you wouldn't mind pasting a snippet of your test, that would also be helpful to figure out what's going wrong. 

I admit, I haven't used Meteor in a while, and so it's possible that the login system has changed slightly. We'll find out. 

-c

**Comment by martpie** [comment]
Hey,

I'm confused, I re-dived into my specs file, and everything is working as expected. I might have missed something this morning when I was working on it, sometimes frustration makes you blind.

Sorry for the inconvenience, great plugin and thanks again !

**Comment by cjsauer** [comment]
>sometimes frustration makes you blind

Happens to the best of us 😄 
Glad you figured it out.
